import type {
  ContentPerformance,
  DashboardStats,
  RecentActivity,
  RevenueByPlatform,
  Task,
  UpcomingContent,
} from "./types";

import { ContentPlatform, ContentStatus, TaskStatus } from "./types";

export const dashboardStats: DashboardStats = {
  totalRevenue: 152840.65,
  monthlyRevenue: 28450.25,
  activeContent: 24,
  pendingTasks: 12,
  teamMembers: 8,
  upcomingPublications: 7,
  revenueGrowth: 15.3,
  taskCompletion: 78,
};

export const revenueByPlatform: RevenueByPlatform[] = [
  {
    platform: ContentPlatform.YOUTUBE,
    amount: 85600,
    percentage: 56,
    growth: 12.5,
  },
  {
    platform: ContentPlatform.TIKTOK,
    amount: 32450,
    percentage: 21,
    growth: 25.3,
  },
  {
    platform: ContentPlatform.INSTAGRAM,
    amount: 21500,
    percentage: 14,
    growth: 8.2,
  },
  {
    platform: ContentPlatform.TWITCH,
    amount: 8920,
    percentage: 6,
    growth: -2.1,
  },
  {
    platform: ContentPlatform.FACEBOOK,
    amount: 5370.65,
    percentage: 3,
    growth: 5.7,
  },
];

export const contentPerformance: ContentPerformance[] = [
  {
    id: "1",
    title: "Como aumentar em 300% seu faturamento",
    platform: ContentPlatform.YOUTUBE,
    revenue: 12500,
    views: 152000,
    engagement: 8.5,
    status: ContentStatus.PUBLISHED,
    published_at: "2024-01-15",
  },
  {
    id: "2",
    title: "Unboxing do novo iPhone 15",
    platform: ContentPlatform.TIKTOK,
    revenue: 8450,
    views: 285000,
    engagement: 12.3,
    status: ContentStatus.PUBLISHED,
    published_at: "2024-01-10",
  },
  {
    id: "3",
    title: "Guia completo de edição",
    platform: ContentPlatform.YOUTUBE,
    revenue: 7200,
    views: 98000,
    engagement: 7.2,
    status: ContentStatus.PUBLISHED,
    published_at: "2024-01-05",
  },
  {
    id: "4",
    title: "Vlog: Viagem ao Japão",
    platform: ContentPlatform.INSTAGRAM,
    revenue: 5320,
    views: 152000,
    engagement: 15.8,
    status: ContentStatus.EDITING,
  },
  {
    id: "5",
    title: "Live coding: Projeto React",
    platform: ContentPlatform.TWITCH,
    revenue: 4210,
    views: 35000,
    engagement: 22.4,
    status: ContentStatus.PUBLISHED,
    published_at: "2024-01-12",
  },
];

export const upcomingContent: UpcomingContent[] = [
  {
    id: "1",
    title: "Review do MacBook M3",
    platform: ContentPlatform.YOUTUBE,
    scheduled_at: "2024-01-25T14:00:00",
    status: ContentStatus.SCHEDULED,
    assigned_to: "Maria Silva",
  },
  {
    id: "2",
    title: "Desafio de 30 dias de exercícios",
    platform: ContentPlatform.TIKTOK,
    scheduled_at: "2024-01-22T18:30:00",
    status: ContentStatus.READY,
    assigned_to: "João Santos",
  },
  {
    id: "3",
    title: "Entrevista com CEO de startup",
    platform: ContentPlatform.YOUTUBE,
    scheduled_at: "2024-01-26T16:00:00",
    status: ContentStatus.EDITING,
  },
  {
    id: "4",
    title: "Tutorial: Animações com Framer Motion",
    platform: ContentPlatform.INSTAGRAM,
    scheduled_at: "2024-01-23T12:00:00",
    status: ContentStatus.SCRIPT,
    assigned_to: "Ana Costa",
  },
  {
    id: "5",
    title: "Live de perguntas e respostas",
    platform: ContentPlatform.TWITCH,
    scheduled_at: "2024-01-24T20:00:00",
    status: ContentStatus.RECORDING,
  },
];

export const pendingTasks: Task[] = [
  {
    id: "1",
    organization_id: "1",
    title: "Revisar roteiro do próximo vídeo",
    status: TaskStatus.TODO,
    priority: 2,
    due_date: "2024-01-20",
    created_at: "2024-01-15",
    updated_at: "2024-01-15",
    metadata: {},
  },
  {
    id: "2",
    organization_id: "1",
    title: "Aprovar design da thumbnail",
    status: TaskStatus.TODO,
    priority: 1,
    assigned_to: "user-2",
    due_date: "2024-01-19",
    created_at: "2024-01-15",
    updated_at: "2024-01-15",
    metadata: {},
  },
  {
    id: "3",
    organization_id: "1",
    title: "Editar vlog da viagem",
    status: TaskStatus.IN_PROGRESS,
    priority: 1,
    due_date: "2024-01-25",
    created_at: "2024-01-14",
    updated_at: "2024-01-16",
    metadata: {},
  },
  {
    id: "4",
    organization_id: "1",
    title: "Agendar posts da semana",
    status: TaskStatus.TODO,
    priority: 0,
    due_date: "2024-01-22",
    created_at: "2024-01-16",
    updated_at: "2024-01-16",
    metadata: {},
  },
  {
    id: "5",
    organization_id: "1",
    title: "Enviar fatura para cliente",
    status: TaskStatus.BLOCKED,
    priority: 2,
    due_date: "2024-01-18",
    created_at: "2024-01-15",
    updated_at: "2024-01-16",
    metadata: {},
  },
];

export const recentActivity: RecentActivity[] = [
  {
    id: "1",
    user: "Carlos Mendes",
    action: "publicou",
    target: "Novo vídeo no YouTube",
    timestamp: "há 2 horas",
    type: "content",
  },
  {
    id: "2",
    user: "Sistema",
    action: "registrou receita",
    target: "R$ 1.250,00 - Afiliado Amazon",
    timestamp: "há 4 horas",
    type: "revenue",
  },
  {
    id: "3",
    user: "Ana Costa",
    action: "completou tarefa",
    target: "Revisão de roteiro",
    timestamp: "há 6 horas",
    type: "task",
  },
  {
    id: "4",
    user: "Mariana Lima",
    action: "adicionou comentário em",
    target: "Vlog da viagem",
    timestamp: "ontem",
    type: "content",
  },
];
